export { default as registerController } from "./auth/registerController";
export { default as loginController } from "./auth/loginController";
export { default as userController } from "./auth/userController";
export { default as refreshTokenController } from "./auth/refreshTokenController";
export { default as logoutController } from "./auth/logoutController";
export { default as bookController } from "./book/BookController";
export { default as readingListController } from "./book/readingListController";
export { default as discussionController } from "./discussion/discussionController";
export { default as bookRatingController } from "./book/bookRatingController";
